code --install-extension vscode.bat
code --install-extension vscode.clojure
code --install-extension vscode.coffeescript
code --install-extension vscode.configuration-editing
code --install-extension vscode.cpp
code --install-extension vscode.csharp
code --install-extension vscode.css
code --install-extension vscode.css-language-features
code --install-extension vscode.dart
code --install-extension vscode.debug-auto-launch
code --install-extension vscode.debug-server-ready
code --install-extension vscode.diff
code --install-extension vscode.docker
code --install-extension vscode.emmet
code --install-extension vscode.extension-editing
code --install-extension vscode.fsharp
code --install-extension vscode.git
code --install-extension vscode.git-base
code --install-extension vscode.github
code --install-extension vscode.github-authentication
code --install-extension vscode.go
code --install-extension vscode.groovy
code --install-extension vscode.grunt
code --install-extension vscode.gulp
code --install-extension vscode.handlebars
code --install-extension vscode.hlsl
code --install-extension vscode.html
code --install-extension vscode.html-language-features
code --install-extension vscode.ini
code --install-extension vscode.ipynb
code --install-extension vscode.jake
code --install-extension vscode.java
code --install-extension vscode.javascript
code --install-extension vscode.json
code --install-extension vscode.json-language-features
code --install-extension vscode.julia
code --install-extension vscode.latex
code --install-extension vscode.less
code --install-extension vscode.log
code --install-extension vscode.lua
code --install-extension vscode.make
code --install-extension vscode.markdown
code --install-extension vscode.markdown-language-features
code --install-extension vscode.markdown-math
code --install-extension vscode.media-preview
code --install-extension vscode.merge-conflict
code --install-extension vscode.microsoft-authentication
code --install-extension ms-vscode.js-debug
code --install-extension ms-vscode.js-debug-companion
code --install-extension ms-vscode.vscode-js-profile-table
code --install-extension vscode.builtin-notebook-renderers
code --install-extension vscode.npm
code --install-extension vscode.objective-c
code --install-extension vscode.perl
code --install-extension vscode.php
code --install-extension vscode.php-language-features
code --install-extension vscode.powershell
code --install-extension vscode.pug
code --install-extension vscode.python
code --install-extension vscode.r
code --install-extension vscode.razor
code --install-extension vscode.references-view
code --install-extension vscode.restructuredtext
code --install-extension vscode.ruby
code --install-extension vscode.rust
code --install-extension vscode.scss
code --install-extension vscode.search-result
code --install-extension vscode.shaderlab
code --install-extension vscode.shellscript
code --install-extension vscode.simple-browser
code --install-extension vscode.sql
code --install-extension vscode.swift
code --install-extension vscode.theme-abyss
code --install-extension vscode.theme-defaults
code --install-extension vscode.theme-kimbie-dark
code --install-extension vscode.theme-monokai
code --install-extension vscode.theme-monokai-dimmed
code --install-extension vscode.theme-quietlight
code --install-extension vscode.theme-red
code --install-extension vscode.vscode-theme-seti
code --install-extension vscode.theme-solarized-dark
code --install-extension vscode.theme-solarized-light
code --install-extension vscode.theme-tomorrow-night-blue
code --install-extension vscode.tunnel-forwarding
code --install-extension vscode.typescript
code --install-extension vscode.typescript-language-features
code --install-extension vscode.vb
code --install-extension vscode.xml
code --install-extension vscode.yaml
code --install-extension ms-ceintl.vscode-language-pack-zh-hans
code --install-extension github.github-vscode-theme
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension formulahendry.code-runner
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension redhat.java
code --install-extension ritwickdey.liveserver
code --install-extension grapecity.gc-excelviewer
code --install-extension wakatime.vscode-wakatime
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension redhat.vscode-yaml
code --install-extension intellsmi.comment-translate
code --install-extension techer.open-in-browser
code --install-extension ms-vscode.live-server
code --install-extension russell.any-rule
code --install-extension humao.rest-client
code --install-extension pkief.material-icon-theme
code --install-extension vscode-icons-team.vscode-icons
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension twxs.cmake
code --install-extension drcika.apc-extension
code --install-extension brandonkirbyson.vscode-animations
code --install-extension be5invis.vscode-custom-css
code --install-extension christian-kohler.npm-intellisense
code --install-extension tyriar.lorem-ipsum
code --install-extension liwenkun.translation
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension naumovs.color-highlight
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension eamodio.gitlens
code --install-extension josetr.cmake-language-support-vscode
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-vscode.makefile-tools
code --install-extension leetcode.vscode-leetcode
code --install-extension wangtao0101.debug-leetcode
code --install-extension ms-azuretools.vscode-docker
